[package]
name = "sts-observer"
version = "0.1.1"
authors = ["roodolv"]
edition = "2021"
license = "LICENSE"

[dependencies]
libsts = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
